### ISSUE TITLE
Provide custom color sources

### ISSUE THREAD

**Issue by kristijanhusak** [nekonako/xresources-nvim#1]
Hi,

I really like this idea of having colors picked up from terminal colors. Haven't tried it yet though.
Only issue is that I'm using kitty terminal, which has it's own configuration, and it's not using xresources.

Would you consider exposing a way to provide custom parser for colors? By default it could work like it's working now, and if someone provides a custom function, use that to parse the colors.

**Comment by nekonako** [comment]
I think use combination of  `cat` to read file configuration of kitty, and `grep` and etc.

then passin it into `lua io.popen`, it's should can to be work.

But idk

**Comment by kristijanhusak** [comment]
Yeah i plan to read kitty configuration file. I just want a way to tell this plugin to use my function to read the colors instead of a built in. I'll set up a PR when I grab some free time.

**Comment by kristijanhusak** [comment]
I gave this a try, it's more less ok, but I'm not getting the results I hope to.
Thanks for help.
